# Generated by Django 6.0.5 on 2026-05-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogsinsights'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogsInsights',
        ),
    ]
